---
queries:
  - name: leaf_l2vpn
    file_path: "reference-designs/3-stage-evpn-vxlan-ebgp-underlay-ibgp-overlay/infrahub/queries/leaf_l2vpn.graphql"

jinja2_transforms:
  - name: leaf-l2vpn-config
    description: "Generate SR Linux L2VPN (mac-vrf + ip-vrf) CLI config for a leaf node"
    query: leaf_l2vpn
    template_path: "reference-designs/3-stage-evpn-vxlan-ebgp-underlay-ibgp-overlay/infrahub/templates/leaf_l2vpn.j2"
